### ISSUE TITLE
Visualizer Viewed - PDP

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#10]
**Page**: https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000950/waterfall-oak?title=Pergo%206.14%20X%203.93%20Ft

When this page was refreshed, the following was in the data layer:
![image](https://user-images.githubusercontent.com/72522616/114066321-998bdc00-9869-11eb-9b1d-d06b83423c79.png)

The "[Visualizer Viewed](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Visualizer%20Viewed.md)" event should only ever fire on PDP when the functionality is immediately seen or if the visitor chooses to use the tool on the page (i.e. when seen via the tab on the PDP).

**Comment by cumeakunne** [comment]
No "Visualizer Viewed" event fired on page refresh.
![image](https://user-images.githubusercontent.com/60761366/115968200-ac0e4280-a504-11eb-963c-0796099ef287.png)

The "Visualizer Viewed" event fires when the Visualizer tool is selected.
![image](https://user-images.githubusercontent.com/60761366/115968503-40c57000-a506-11eb-94a4-88c43eddfac9.png)
