### ISSUE TITLE
CTA Link Clicked - Blank values in data layer

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#101]
On the CTA Link Clicked event, linkContainer and linkRegion are both passed as "". This was observed when clicking the "Shop" link from a PLP. 

![image](https://user-images.githubusercontent.com/83465286/122777348-90f45080-d271-11eb-9652-21729b4d38c7.png)

**Comment by nate-wolfe** [comment]
This data isn't available for the CTA Link Clicked event, because the CTAs could be anywhere in the site. The values were set to empty so that the overall structure of the event would closer resemble other link events.

**Comment by jasonegan** [comment]
@savithanuguri Can you give a couple of examples of CTAs so that I can give some example values?

**Comment by jasonegan** [comment]
@nate-wolfe As we discussed, you can just concatenate the text before the URL path in the linkID variable. So a shop button might look like:

"shop|[path]"

**Comment by nate-wolfe** [comment]
In dev:
![image](https://user-images.githubusercontent.com/81365619/123286017-89d07b00-d4db-11eb-8d35-6112fabe746d.png)

**Comment by nate-wolfe** [comment]
In staging:
![image](https://user-images.githubusercontent.com/81365619/123314137-3587c400-d4f8-11eb-8878-148404df3e79.png)

**Comment by ryanAtSdi** [comment]
@nate-wolfe - can we at least pass header/body/footer to linkRegion?

**Comment by nate-wolfe** [comment]
@ryanAtSdi - We can’t. The event fires from a location in which it is only aware of the text of the link clicked and the URL the link redirects to. This was achieved by tracking every link clicked on the site. These links could be anywhere on the site, and the event would be completely unaware of the context.

**Comment by ryanAtSdi** [comment]
Ok, I'll go ahead and close this out then.
