### ISSUE TITLE
Page Load Started - pageView and Previous Page Name (p6, v56) not firing

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#102]
Not seeing any of these 3 sent on server call, expecting to see each time there is page load started. 

![image](https://user-images.githubusercontent.com/83465286/123133599-85418f00-d415-11eb-9411-398e28407c6f.png)

**Comment by rmessickSDI** [comment]
added plugin.  porp6 and evar56 are there now.  pageview is out of box.
![image](https://user-images.githubusercontent.com/78565036/123327586-33c1fe80-d500-11eb-8164-37fc6b08d917.png)

**Comment by ryanAtSdi** [comment]
Confirming this is correct now:
![image](https://user-images.githubusercontent.com/83465286/123698852-34ba9f00-d824-11eb-959a-342c43d5c362.png)
