### ISSUE TITLE
Visualizer Viewed - productNumber and sku same for all products in array on PDPs

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#103]
On PDPs only, the productNumber and sku is identical for every product in the product array on the Visualizer Viewed event. See below:
![image](https://user-images.githubusercontent.com/83465286/123152132-dd828c00-d429-11eb-98ef-8379be09831e.png)

**Comment by nate-wolfe** [comment]
In dev:
![image](https://user-images.githubusercontent.com/81365619/123289414-7541b200-d4de-11eb-83b6-b905e9fbcf1e.png)

**Comment by nate-wolfe** [comment]
In staging:
![image](https://user-images.githubusercontent.com/81365619/123314045-1c7f1300-d4f8-11eb-81e2-6386f1aa601b.png)
