### ISSUE TITLE
custKey - Data layer has incorrect value on all related events

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#104]
custKey value is wrong for all events where it's present, which includes:

- User Detected - set to null
- User Signed In - set to "guest", despite being signed in
- Visitor Signed Out - undefined

![image](https://user-images.githubusercontent.com/83465286/124670798-21d64900-de7a-11eb-8e42-e0a985504791.png)

**Comment by ryanAtSdi** [comment]
@savithanuguri - just wanted to confirm that e49 should be set to "guest" when no ID is available (i.e., customer logged out). If so, I can close this out.

**Comment by nate-wolfe** [comment]
In staging:
![image](https://user-images.githubusercontent.com/81365619/125314258-0947b200-e304-11eb-8bac-ada49c92983a.png)
