### ISSUE TITLE
Product Interaction Occurred - PDP Load

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#11]
**Page**: https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000950/waterfall-oak?title=Pergo%206.14%20X%203.93%20Ft

When this page was refreshed, the following was in the data layer:
![image](https://user-images.githubusercontent.com/72522616/114066321-998bdc00-9869-11eb-9b1d-d06b83423c79.png)

The "[Product Interaction Occurred](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Product%20Interaction%20Occurred.md)" event should only ever fire when a visitor actively interacts with the elements on the that are deemed as interactions. This event should not fire on the load of the page.

**Comment by cumeakunne** [comment]
A page refresh did not fire "Product Interaction Occurred" event.
![image](https://user-images.githubusercontent.com/60761366/115972022-0796fb00-a51a-11eb-8486-dadb68f47ac3.png)
