### ISSUE TITLE
Product Viewed - PDP

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#12]
**Page**: https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000950/waterfall-oak?title=Pergo%206.14%20X%203.93%20Ft

When this page was refreshed, the following was in the data layer:
![image](https://user-images.githubusercontent.com/72522616/114066321-998bdc00-9869-11eb-9b1d-d06b83423c79.png)

The "[Product Viewed](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Product%20Viewed.md)" event should only fire on the load of the page, after page Load Started and before Page Load Completed.

**Comment by savithanuguri** [comment]
Page Load Started, User Detected, Page Load Completed all three events are in the metadata component. This component is in the header section of all pages.

**Comment by cumeakunne** [comment]
When the page is refreshed, one instance of the "Product Viewed" event was fired between the "Page Load Started" and "Page Load Completed" events.
![image](https://user-images.githubusercontent.com/60761366/115965691-4a47db80-a4f8-11eb-8767-71ebf1afe5aa.png)
