### ISSUE TITLE
Request Quote Form - PDP

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#13]
The reporting data looks okay here, but when trying to test the request quote form at https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000950/waterfall-oak?title=Pergo%206.14%20X%203.93%20Ft&tab=collection, there are numerous JS errors in the console that I'm guessing are stopping me from completing the form:
![image](https://user-images.githubusercontent.com/72522616/114069925-824eed80-986d-11eb-92d7-3a8a6df3fcd9.png)

Additionally, the form itself does not name the fields, so I'm not sure what to fill in in order to submit the form:
![image](https://user-images.githubusercontent.com/72522616/114070058-a0b4e900-986d-11eb-997a-79085cd24aab.png)

 Please advise when we can test this form.

**Comment by savithanuguri** [comment]
If the retailer is not selected then the Request quote CTA will be disabled in PDP. This functionality already implemented and deployed in Dev. We will deploy in staging after completing Unit Testing.

**Comment by rmessickSDI** [comment]
@savithanuguri Seems like all of the products show the store as "Lowe's" even if you set a different store. The quote button is supposed to be there for the speciality stores.

**Comment by savithanuguri** [comment]
Lowes logo will be indicating that product retailer. Not the retailer that we selected. 
Request quote button will appear for Independent retailer products. 
https://staging.pergoflooring.com/shop/rigid-vinyl/extreme-enhanced/detail/PT003-980/grey-opal?title=Pergo%20Extreme%20Wood%20Enhanced. All most all products under Vinyl plank will have a Request Quote button. Pergo Outlast collection will have the Home Depot product.
