### ISSUE TITLE
Onsite Search Performed - Update to Spec

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#15]
There was something left out on our part that needs to be added to this event. SDI has added a new var to "O[nsite Search Performed](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Onsite%20Search%20Performed.md)," for the search phrase used by the visitor. You will see this in the "searchTerm" variable in the data layer spec. Thanks.

**Comment by rmessickSDI** [comment]
![image](https://user-images.githubusercontent.com/78565036/116300185-399b9d80-a764-11eb-8174-09dea59f23c9.png)
