### ISSUE TITLE
Product Listing Item Clicked Not Firing - PLP

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#17]
Example Page: [PLP Page](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Product%20Listing%20Item%20Clicked.md)

Not seeing the "Product Listing Item Clicked" event fire when clicking the "Shop" button or the "Read more" link to a PDP from the PLP pages.

**Comment by cumeakunne** [comment]
"Product Listing Item Clicked" event fired when clicking the "Shop" button from PLP to PDP.
![image](https://user-images.githubusercontent.com/60761366/115971538-031d1300-a517-11eb-8b48-f33f4c8111b8.png)

"Product Listing Item Clicked" event fired when clicking the "Read more" link from PLP to PDP.
![image](https://user-images.githubusercontent.com/60761366/115971555-0b754e00-a517-11eb-915c-d082c510f8c1.png)
