### ISSUE TITLE
Page Load Started - PDP Page Name

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#18]
On [PDPs](https://staging.pergoflooring.com/shop/laminate/outlast/detail/LF000982/snowbird-walnut?title=Outlast%205X47), there is currently a single page name of "pergo: product-detail"

Can this be updated for PDPs to end with the product name? As an example for the page linked above, the page name would be "pergo: product-detail: pergo outlast+ with spillprotect"

**Comment by savithanuguri** [comment]
we added Page load started the event in metadata component means in the header. It is not possible to add the Collection name in the page load started the event.

**Comment by cumeakunne** [comment]
This appears to still have the same page name.
![image](https://user-images.githubusercontent.com/60761366/114936921-16d7c380-9e0b-11eb-9525-35a0429efb9e.png)

**Comment by cumeakunne** [comment]
The pageName is now passed the distinct Page Title.
![image](https://user-images.githubusercontent.com/60761366/115971757-46c44c80-a518-11eb-8be5-fad496a8157b.png)

Some PDP pageNames contain the url's "%20". Is it possible to remove these url additions?
![image](https://user-images.githubusercontent.com/60761366/115971846-d538ce00-a518-11eb-86b6-f4ae6c21b21c.png)

**Comment by cumeakunne** [comment]
Some PDPs, that do not show the page name in the visible breadcrumbs, do not capture a unique pageName. These pages were reached from the PLP clicking the "Read More" link.
![image](https://user-images.githubusercontent.com/60761366/116494937-ec0c5700-a86f-11eb-8cae-4767d214e355.png)

The same PDP shows the page name in the visible breadcrumbs when reached by the "Shop" button from the PLP, and captures a unique pageName with the url's "%20".
![image](https://user-images.githubusercontent.com/60761366/116495811-acdf0580-a871-11eb-8fa5-be6310dc9ad3.png)

**Comment by savithanuguri** [comment]
@rmessickSDI ,
We updated page names based on URL. 
![image](https://user-images.githubusercontent.com/82102160/117207506-03909600-adc2-11eb-85df-7d584650221e.png)
