### ISSUE TITLE
Product Viewed - Data Layer Order

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#19]
At this time, the "[Product Viewed](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Product%20Viewed.md)" event is firing after "Page Load Completed." This event needs to fire between "Page Load Started" and "Page Load Completed." 

![image](https://user-images.githubusercontent.com/72522616/114081626-c98fab00-987a-11eb-99c7-155db5b5e288.png)

**Comment by rmessickSDI** [comment]
Checked https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000951/hermosa-oak?title=Pergo%20Portfolio%20+WetProtect with slow 3g throttle and still loads correctly.

![image](https://user-images.githubusercontent.com/78565036/116290413-0d2e5400-a759-11eb-939d-689636c90715.png)

**Comment by rmessickSDI** [comment]
@savithanuguri @jasonegan Looks like `Product Viewed` is happening after `Page Load Completed` on this page.  Can we ensure that it loads before it?

https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000967/rustic-smoked-chestnut?title=Pergo%20Portfolio%20+WetProtect
![image](https://user-images.githubusercontent.com/78565036/117203957-4a2bc380-adb5-11eb-88b5-6ab68b9d0ac8.png)
