### ISSUE TITLE
Product Viewed - Price Tier Undefined

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#20]
priceTier is currently undefined in the data layer on [PDP](https://staging.pergoflooring.com/shop/laminate/outlast/detail/LF000941/wild-natural-walnut?title=Outlast%205X47):

![image](https://user-images.githubusercontent.com/72522616/114082518-d660ce80-987b-11eb-8eb3-c88c1519e330.png)

**Comment by cumeakunne** [comment]
@savithanuguri is "good" an expected value for price tier?
