### ISSUE TITLE
Product Viewed - trademarkTechnology Undefined/Incorrect

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#21]
trademarkTechnology is currently undefined in the data layer on [PDP](https://staging.pergoflooring.com/shop/laminate/outlast/detail/LF000941/wild-natural-walnut?title=Outlast%205X47):

![image](https://user-images.githubusercontent.com/72522616/114085322-35741280-987f-11eb-8856-89e53aeb4245.png)

**Comment by cumeakunne** [comment]
![Pergo Tag QA_21_trademarkTech](https://user-images.githubusercontent.com/60761366/115275118-6a9a2380-a10f-11eb-9287-16cfd2e97ebd.png)

**Comment by ryanAtSdi** [comment]
Opening this back up as I'm seeing this issue again:
![image](https://user-images.githubusercontent.com/83465286/119055611-f57c7100-b98e-11eb-84c5-5da67c8156a3.png)

**Comment by ryanAtSdi** [comment]
@savithanuguri - I'm still not seeing this correctly on Pergo Extreme pages (may be others as well):

**URL**
https://staging.pergoflooring.com/shop/rigid-vinyl/extreme-enhanced/detail/PT003-433/antelope?title=Pergo%20Extreme%20Wood%20Enhanced
**Screenshot**
![image](https://user-images.githubusercontent.com/83465286/119409077-5caa6600-bcac-11eb-9121-bca607695e98.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119755640-56fd7d80-be70-11eb-9435-94bcf8ed53d9.png)
updated in staging

**Comment by ryanAtSdi** [comment]
@savithanuguri - from the screenshot you provided the value is defined, but still incorrect. Data layer should contain something along the lines of SpillProtect, WetProtect, etc. From what I can see going through the site, trademarkedTechnology is being set to "Scratch Resistant. Waterproof. Dent Resistant" in every product string.

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119991132-249a7000-bf97-11eb-9160-d13dc7e07a2d.png)
@ryanAtSdi , available in staging

**Comment by ryanAtSdi** [comment]
@savithanuguri - I'm seeing cases where SpillProtect in particular is being listed twice. 

![image](https://user-images.githubusercontent.com/83465286/120000692-b3f45300-bf98-11eb-9a6a-3f4a09369f70.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/120038970-1289f300-bfd2-11eb-98fa-d3338b3c5ce2.png)
Removed multiple times of trademark technology
@ryanAtSdi
