### ISSUE TITLE
Location Listing Displayed - Refresh Not Firing Data Layer

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#22]
If a [location detail page](https://staging.pergoflooring.com/shop/find-a-retailer/20593/Fraziers-Flooring-Inc) is refreshed/reloaded, the "appEventData" data layer contains no events:
![image](https://user-images.githubusercontent.com/72522616/114086630-d7482f00-9880-11eb-9976-fc1e7da51214.png)

**Comment by jasonegan** [comment]
Just a heads-up here, @savithanuguri, as I know you might still be working on this one, but I just noticed this event was firing twice on the load of the listings page:

![image](https://user-images.githubusercontent.com/72522616/114455852-315f3200-9baa-11eb-9e26-e98a5d7302ee.png)

That last one there should not be firing on the page load.

**Comment by jasonegan** [comment]
Also, it looks like only the second "Location Listing Displayed" event actually contains any data. So, either the first, blank event is removed, leaving the one firing after Page Completed, OR there is only one "Location Listing Displayed" event that is fired before Page completed, but that contains the data. Just let us know which will work best.

**Comment by nate-wolfe** [comment]
It'll be easiest to implement only the second event with the data, after page load completed. The data isn't available to the page until after page load completed has already fired.

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/117908788-1108bd00-b2a7-11eb-8803-6268f607b8b2.png)
@jasonegan , after refresh data is available.

**Comment by ryanAtSdi** [comment]
@savithanuguri , @jasonegan - to clarify, should another set of page load events fire on refresh, or was the issue just that the location info was erased upon refresh?

**Comment by savithanuguri** [comment]
@ryanAtSdi     location info was erased upon refresh

**Comment by ryanAtSdi** [comment]
Thank you, @savithanuguri !
