### ISSUE TITLE
Location Listing Item Clicked - Analytics Beacon Double-firing

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#23]
When on a [location detail page](https://staging.pergoflooring.com/shop/find-a-retailer/20593/Fraziers-Floorin), click the "Make this my retailer" link. This is double firing an Adobe Analytics beacon.

**Comment by rmessickSDI** [comment]
Only firing 1 now that Launch embed is in header.
![image](https://user-images.githubusercontent.com/78565036/115599489-4cfcc380-a2a1-11eb-8194-ed231ceb19a1.png)
