### ISSUE TITLE
Location Listing Item Clicked - Missing Data Layer Items

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#24]
This fires when a visitor clicks the "Make this my retailer" link on a [location detail page](https://staging.pergoflooring.com/shop/find-a-retailer/20593/Fraziers-Flooring-Inc). There are no values for locationID and locationType.

![image](https://user-images.githubusercontent.com/72522616/114087513-f98e7c80-9881-11eb-8656-8b022ecfb67c.png)

1. Is there no "ID" value present, or is "locationName" alone sufficient?
2. Can we populate locationType here with the dealer type (Edge, etc.)?

**Comment by cumeakunne** [comment]
![image](https://user-images.githubusercontent.com/60761366/115086546-794bc500-9eda-11eb-8fce-8b396a4459ca.png)

**Comment by cumeakunne** [comment]
The Home Depot is a big-box retail store and is correctly assigned the locationType ("Retail Store"). See Home Depot Screenshot comment. In contrast, Frazier's Flooring Inc is a specialty store and should be assigned ("Specialty Store") for locationType. 
![Pergo Tag QA_locationType](https://user-images.githubusercontent.com/60761366/115277208-fca32b80-a111-11eb-830b-7bbba238b032.png)

**Comment by rmessickSDI** [comment]
![image](https://user-images.githubusercontent.com/78565036/116301985-44573200-a766-11eb-9fe9-7083d19e977c.png)
