### ISSUE TITLE
Social Brand Followed - Double Firing

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#26]
The social links in the footer of the site, when clicked, are firing the "Exit Link Clicked" and the "Social Brand Followed" events.
![image](https://user-images.githubusercontent.com/72522616/114091746-0b265300-9887-11eb-90b3-d8759f2d0638.png)

These events are firing only once in the data layer (and the vars look correct). However, they are double-firing the analytics beacons.

**Comment by rmessickSDI** [comment]
Does not look like an issue anymore.  I think it is from launch being in header.
