### ISSUE TITLE
Visualizer Viewed - Product Information on Dedicated Visualizer Page

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#27]
When a visitor sees the [standalone visualizer page](https://staging.pergoflooring.com/discover/visualizer?productType=Laminate%20Wood), this is not specific to any product as it is not on a PDP. In the case of this standalone visualizer page, can you set the "productID" to a static value of "Visualizer?" This will make reporting more useful.
![image](https://user-images.githubusercontent.com/72522616/114093526-3742d380-9889-11eb-9eb8-f92127b20649.png)

**Comment by cumeakunne** [comment]
![image](https://user-images.githubusercontent.com/60761366/115270100-ff018780-a109-11eb-97ac-8913c3c95750.png)
