### ISSUE TITLE
User Registered - custKey Not Set/Log-in Status

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#28]
Upon the firing of the "User Registered" event, the "custKey" variable is not set:
![image](https://user-images.githubusercontent.com/72522616/114094310-28a8ec00-988a-11eb-8d9b-f326c938f7fa.png)

Will this not be set at this time, or can this be updated to include the customer ID value?

Upon successful registration, the visitor is automatically logged in. So, the value of the "loginStatus" should be "logged in"

**Comment by savithanuguri** [comment]
After Successful registration user is redirecting to the log-in screen. So no cust key is set, and status is logged out

**Comment by rmessickSDI** [comment]
I signed up with another email and when creating user still does not have custKey
![image](https://user-images.githubusercontent.com/78565036/117208101-59f9d680-adba-11eb-8bcc-6685bdcd0c2f.png)

**Comment by savithanuguri** [comment]
@rmessickSDI , After registering user will redirect to the login page. If the user is logged in then, custkey is available. 
Can you please confirm after login also you are not seeing custkey

**Comment by rmessickSDI** [comment]
So for the event `User Registered` we will not have the custKey?

**Comment by savithanuguri** [comment]
@rmessickSDI , until login, user will not have custkey

**Comment by rmessickSDI** [comment]
removing user id from adobe launch since it is unavailable.
