### ISSUE TITLE
Listing Filter Added - Missing From Location Listings

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#30]
The "[Listing Filter Added](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Listing%20Filter%20Added.md)" event needs to fire when a visitor chooses one of the headers at the top of the location listings (https://staging.pergoflooring.com/shop/find-a-retailer?zip=37919&filter=homedepot&page=1).

- The "listingType" in the data layer here would be "Location"
- "filterList" would be something like "retailer type~the home depot"

![image](https://user-images.githubusercontent.com/72522616/114218333-47b18780-9937-11eb-9802-505b9a0f2fc0.png)

**Comment by cumeakunne** [comment]
listingType  and filterList capture expected values upon header selection.
![image](https://user-images.githubusercontent.com/60761366/115075110-99728880-9ec8-11eb-867b-a9aede0f12de.png)
![image](https://user-images.githubusercontent.com/60761366/115074457-b8244f80-9ec7-11eb-9f1d-9249048aa689.png)
![image](https://user-images.githubusercontent.com/60761366/115071666-8a89d700-9ec4-11eb-9214-3548e75698e1.png)
![image](https://user-images.githubusercontent.com/60761366/115073596-8eb6f400-9ec6-11eb-85fe-f35f13b7a6ac.png)
