### ISSUE TITLE
Listing Filter Removed

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#31]
**Updated**: As per Nate, "Listing Filter Removed" should fire when a visitor changes a product filter back to the default option. Additionally, the "Listing Filter Removed" event would also need to fire on the retailer listing page if the visitor changes the filter back to "View All."

As far as I can tell, filters are dropdowns or the buttons on the retailer search. So, it doesn't look like there's really a way to "remove" a filter. If this is correct then it seems that we do not need the [Listing Filter Removed](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Listing%20Filter%20Removed.md) specification. Can you confirm this for us?

**Comment by nate-wolfe** [comment]
A filter is considered "removed" when the dropdown is taken from a selected value back to the default. For example, selecting "Dark" from the Color dropdown, then selecting "Color" again. This is at least how I implemented it. Some values can't change back like this, but others can.

**Comment by jasonegan** [comment]
Thanks @nate-wolfe. @savithanuguri I have updated the description above as per Nate's comment.

**Comment by rmessickSDI** [comment]
This looks to behaving correctly based on the above.  
![image](https://user-images.githubusercontent.com/78565036/116298828-8ed6af80-a762-11eb-8a8a-2ecd8bd6c171.png)
