### ISSUE TITLE
Location Detected - Updated Specification/Not Firing

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#32]
Added "locationType" and "locationId" to the "[Location Detected](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Location%20Detected.md)" specification if these two values can also be set as a part of this event.

Additionally, we are not seeing this event fire when browsing the site after having logged in and having a retailer chose as "My Retailer" for the account.

**Comment by savithanuguri** [comment]
@jasonegan , location detected event is having location id and location type in staging.

![image](https://user-images.githubusercontent.com/82102160/117203665-456b0d80-adbd-11eb-80cd-cef3ece006e3.png)

**Comment by ryanAtSdi** [comment]
Same question as on ticket #29 - how should locationId be passed?

**Comment by nate-wolfe** [comment]
The [specification](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Location%20Detected.md) lists it as a string. I'll get that fixed as soon as possible

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/117714517-0ebe3a00-b1a5-11eb-859c-d090e24020a7.png)
@ryanAtSdi , changed location id to string
