### ISSUE TITLE
Location Selected - "Make My Retailer" - locationDeterminationMethod Undefined

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#36]
When on the [listing of retailers](https://staging.pergoflooring.com/shop/find-a-retailer?zip=37919&page=1&filter=all), and you click the "Make My Retailer" button for a retailer, the "[Location Selected](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Location%20Selected.md)" event fires and the "locationDeterminationMethod" should be set to "Customer Selection". At this time, this value is undefined.

![image](https://user-images.githubusercontent.com/72522616/114224951-c0b4dd00-993f-11eb-9994-cfdb0ea72a7b.png)

![image](https://user-images.githubusercontent.com/72522616/114224999-cf9b8f80-993f-11eb-8a60-2c9499f2e597.png)

**Comment by cumeakunne** [comment]
For the "Location Selected" event, "locationDeterminaitonMethod" is passed "Customer Selection".
![image](https://user-images.githubusercontent.com/60761366/115969247-09f15900-a50a-11eb-8425-e96d60e714f9.png)
