### ISSUE TITLE
Location Selected - Geo Location Selection - Not Firing

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#37]
When a visitor visits the site for the first time (or after their cookies have expired, before logging back in), their assigned location will/can be determined by automatic Geo look-up. When this happens and the visitor is assigned a location, the "[Location Selected](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Location%20Selected.md)" event should be fired.

Note 1 > The "locationDeterminationMethod" here should also be set to either "Automatic - IP Based" OR "Automatic - Device Based"

Note 2 > After a visitor logs in or logs out, this event would fire again with the appropriate value set in "locationDeterminationMethod"as per the specification referenced above.

**Comment by rmessickSDI** [comment]
![image](https://user-images.githubusercontent.com/78565036/117144148-36fa0300-ad77-11eb-96b4-7bb6d2f1ad03.png)
unable to test the geo.  Not sure why locationId is blank.

**Comment by savithanuguri** [comment]
@rmessickSDI , tested in staging environment.
![image](https://user-images.githubusercontent.com/82102160/117186167-90c6f100-ada8-11eb-8a3a-7f75b2ba0c55.png)

**Comment by ryanAtSdi** [comment]
@savithanuguri , @rmessickSDI - is locationId supposed to be a number or string? Image above shows string, but I'm seeing number:
