### ISSUE TITLE
Video Names

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#38]
The [Install FAQ](https://staging.pergoflooring.com/install-diy#faq) page contains several videos. These videos are passing URL-based video names such as:

![image](https://user-images.githubusercontent.com/72522616/114406295-6bfaa780-9b75-11eb-8aaa-692a198a2b3c.png)

Can this video name (as a part of the [Video Started](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Video%20Started.md)/[Video Milestone Reached](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Video%20Milestone%20Reached.md)/[Video Completed](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Video%20Completed.md)) be updated in what is passed in the data layer to be a more concise value such as the following?

          "MohawkResidential/How to Horizontally Install Pergo Laminate Flooring On Your Walls"

I believe this is essentially just part of the URL path, with the URL encoding removed.

**Comment by cumeakunne** [comment]
videoName is passed a concise video description for "Video Started", "Video Milestone Reached", and "Video Completed" events.
![image](https://user-images.githubusercontent.com/60761366/115968752-55eece80-a507-11eb-81d9-1453950130b5.png)
