### ISSUE TITLE
Video Started - Do Not Fire after Unpause

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#39]
At this time, if you pause and unpause the video player on the [Install FAQ page](https://staging.pergoflooring.com/install-diy#faq), the "[Video Started](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Video%20Started.md)" event is firing again. We do not need this event firing here. It should only fire on the initial start of a video.

**Comment by cumeakunne** [comment]
The "Video Started" event fires at the initial start of the video and does not fire again after each pause and unpause of the video.
![image](https://user-images.githubusercontent.com/60761366/115966071-11106b00-a4fa-11eb-82e6-7ed85681c16e.png)
