### ISSUE TITLE
Video Milestone Reached - Not Firing

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#40]
On the [Install FAQ page](https://staging.pergoflooring.com/install-diy#faq), we are not seeing the "[Video Milestone Reached](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Video%20Milestone%20Reached.md)" event firing at the 25%, 50% and 75% completion steps of the videos.

**Comment by cumeakunne** [comment]
![mohawk_test40_VideoMilestoneV1](https://user-images.githubusercontent.com/60761366/115964855-68abd800-a4f4-11eb-899f-a861dfc394ab.png)
![mohawk_test40_VideoMilestoneV2](https://user-images.githubusercontent.com/60761366/115964857-6b0e3200-a4f4-11eb-9394-db5ef104d3a1.png)
