### ISSUE TITLE
Location Detected - Add New Vars

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#42]
We've manually added "locationType" and "locationId" to the data layer specification. Can you add these to the Launch rules for the "[Location Detected](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Location%20Detected.md)" event in Adobe Launch?

**Comment by rmessickSDI** [comment]
Need to find a way to add Location Type to AAPSB since not in apollo but not affect apollo pushes.

**Comment by rmessickSDI** [comment]
Apollo added.  Updated event and pushed again.  Looks like it worked.
![image](https://user-images.githubusercontent.com/78565036/120675523-c409a800-c45a-11eb-8f65-d081be92e3b1.png)

**Comment by ryanAtSdi** [comment]
@rmessickSDI - I'm seeing locationId passed via v34, but not seeing locationType. See screenshot below:

URL: https://staging.pergoflooring.com/shop?installation=&look=&page=1 -- I went through the site, and experience here is consistent with what I'm seeing on other pages.

Screenshot:
![image](https://user-images.githubusercontent.com/83465286/120812865-01317100-c513-11eb-9004-205222af118b.png)

**Comment by rmessickSDI** [comment]
Sorry, Ryan.  I went and checked this is apollo and pushed again.  It is there now.  
![image](https://user-images.githubusercontent.com/78565036/121218179-24785b00-c848-11eb-9161-b16c1d86018e.png)

**Comment by ryanAtSdi** [comment]
Confirming this is good now:
![image](https://user-images.githubusercontent.com/83465286/121240782-5695b700-c860-11eb-9e18-248334af8307.png)
