### ISSUE TITLE
Product Interaction Occurred - Swatch Click

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#43]
At the top of the [PDP page](https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000949/huntington-oak?title=Pergo%206.14%20X%203.93%20Ft) there are color swatches that a visitor can click:

![image](https://user-images.githubusercontent.com/72522616/114456742-34a6ed80-9bab-11eb-8b26-749e75befd94.png)

When a swatch is clicked, it should fire a single "Product Interaction Occurred" event. However, the click on the swatch is currently firing twice. This second firing (which looks to be related to the visualizer) should not fire on the click of the swatch here.

![image](https://user-images.githubusercontent.com/72522616/114456975-80f22d80-9bab-11eb-9ebe-c8828ed451cd.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/115329307-2125f480-a160-11eb-8bce-d27c5f5bc22a.png)

**Comment by cumeakunne** [comment]
All swatch clicks fired a single "Product Interaction Occurred" event.
![image](https://user-images.githubusercontent.com/60761366/115965382-03a5b180-a4f7-11eb-93d3-c0f3155cb17c.png)
