### ISSUE TITLE
Product Interaction Occurred - Tab Clicks

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#44]
[PDP pages](https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000950/waterfall-oak?title=Pergo%25206.14%2520X%25203.93%2520Ft&tab=collection) have different tabs on them, this should fire the "[Product Interaction Occurred](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Product%20Interaction%20Occurred.md)" event when clicked, but are currently not firing the event upon this interaction.

![image](https://user-images.githubusercontent.com/72522616/114457461-0c6bbe80-9bac-11eb-9370-2d20058c68ea.png)

**Comment by cumeakunne** [comment]
All tab selections fire the "Product Interaction Occurred" event.
![image](https://user-images.githubusercontent.com/60761366/115971164-d7992900-a514-11eb-9130-99c045a4ce23.png)
