### ISSUE TITLE
Visualizer Viewed - PDP Tab

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#45]
On [PDP pages](https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000951/hermosa-oak?title=Pergo%205.23%20X%203.93%20Ft), when a visitor clicks the Visualizer tab and the visualizer is viewed, the "[Visualizer Viewed](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Visualizer%20Viewed.md)" event should fire. However, this is not firing at this time.

**Comment by cumeakunne** [comment]
The "Visualizer Viewed" event does not fire under expected use case. 

1. When the page refreshes and the Visualizer Tab "Visualize it" is selected the event does not fire. If the 'Visualize it' or 'View In Room' buttons are then selected, the event does not fire.
![image](https://user-images.githubusercontent.com/60761366/115970855-3cec1a80-a513-11eb-8b0d-c94d1d2b47b3.png)

2. After completing Step 1, if tabs "The Collection" or "Customer Reviews" are selected then the "Visualizer Viewed" event is fired.
![image](https://user-images.githubusercontent.com/60761366/115970788-c5b68680-a512-11eb-9aa0-99867d9860f2.png)

**Comment by cumeakunne** [comment]
The "Visualizer Viewed" event fires for the "Visualize it" button click. Need this to also fire for the Visualizer Tab selection as it's tied to a specific Adobe Analytics event.
![image](https://user-images.githubusercontent.com/60761366/116558797-d168cb00-a8cd-11eb-8fa7-94f5f0aabc96.png)

**Comment by savithanuguri** [comment]
@cumeakunne @rmessickSDI 
![image](https://user-images.githubusercontent.com/82102160/117204936-f1f9bf00-adbe-11eb-992b-b2d5b1fd9382.png)
Tested for 3 ways, one is with "Visualize it" button click, "Visualize it" tab click and View in Room also.
