### ISSUE TITLE
Adobe Launch Header Deployment

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#48]
Can we have the Adobe Launch header deployed directly in the "Head" tag of the site? We're thinking that the current method of injection may be resulting in some odd things with Adobe Analytics.

**Comment by rmessickSDI** [comment]
Can we just have it have `async` and not `async=""`?  async is a boolean.

![image](https://user-images.githubusercontent.com/78565036/116296544-f9d2b700-a75f-11eb-8481-ec392a4ef2a9.png)

etc
<script src="//assets.adobedtm.com/13496781d41f/b9bd22ab52ce/launch-f98e549ff183.min.js" async></script>

https://github.com/searchdiscovery/mohawk-flooring-dl-spec

**Comment by rmessickSDI** [comment]
@savithanuguri Did you see my comments above?  I checked and still see it as 

view-source:https://staging.pergoflooring.com/

![image](https://user-images.githubusercontent.com/78565036/116605743-6a5f0c80-a8f5-11eb-82d2-3299172702e5.png)

**Comment by savithanuguri** [comment]
@rmessickSDI , As discussed added async=true.
![image](https://user-images.githubusercontent.com/82102160/118313050-42100a00-b4c0-11eb-9dec-3bdfc0d57ac2.png)
Please check and let me know for changes
