### ISSUE TITLE
Page Load Started: Search - Page Name/Type/Breadcrumb

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#49]
When a search results page is viewed, the page object is as follows:
![image](https://user-images.githubusercontent.com/72522616/116183068-3fa16800-a6eb-11eb-9dac-aad945cfbf5a.png)

- pageType here needs to be "search"
- pageName here needs to follow the naming convention of "pergo:search:[phrase used]"

The breadcrumb value here should pull it's value from what the breadcrumb looks like on the page:
![image](https://user-images.githubusercontent.com/72522616/116183285-99099700-a6eb-11eb-9f9b-ab19e8043226.png)

- breadCrumb here on search result pages should be "pergo:home > search"

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/118067827-54c6f980-b36f-11eb-8388-e3c28c094321.png)
@jasonegan , staging chnages are available
