### ISSUE TITLE
Page Load Started - Page Naming Convention (Overall)

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#50]
There are a lot of pages on the site with a page name of "pergo:single-column", etc on the site at this time. Can you update the page names and page types to follow the naming convention below?

brand:siteSection:pageType:siteSubsection/collection:siteSubsubsection/product
pergo:shop:product-detail:timbercraft:cliffside-oak

OR

brand:siteSection/productType:siteSubsection/collection:siteSubsubsection/product
pergo:laminate:timbercraft:cliffside-oak

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/117206230-97616280-adc0-11eb-91ae-170ebc1f40c7.png)
@jasonegan , its updated in staging.
