### ISSUE TITLE
Location Detected - firing after Page Load Completed

### ISSUE THREAD

**Issue by rmessickSDI** [searchdiscovery/mohawk-flooring-dl-spec#51]
Can we fire "Location Detected" before "Page Load Completed".  We will need this for it to be a part of the 1 beacon call we are sending.

https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Location%20Detected.md

example page:
https://staging.pergoflooring.com/shop?installation=&look=&page=1&shade=

**Comment by savithanuguri** [comment]
LOcation detected or all other events will be called after Page load completed. We are adding Page load started, User detected and Page load completed in the metadata component. This component will be initialized before other components.

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/117451811-02ba4a00-af11-11eb-9f9e-f6b077eaf730.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/117714379-d9195100-b1a4-11eb-9efe-86cc5c6d04b8.png)
@rmessickSDI , code is available in staging
