### ISSUE TITLE
Add to Cart Button Errors - PLP & PDP

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#53]
Clicking the Add Samples to Cart button results in JS error, preventing QA of the Sample Checkout Started event (lines 47-53 in QA document):
![image](https://user-images.githubusercontent.com/83465286/116753440-b6c94b80-a9cc-11eb-9bb8-e6e450cb9bd5.png)
URL: https://staging.pergoflooring.com/shop?installation=&look=&page=1&shade=

Similar issues exist for Add to Cart button on PDP, preventing QA for Checkout Started event (lines 40-46):
![image](https://user-images.githubusercontent.com/83465286/116753944-8b932c00-a9cd-11eb-84db-5c9d6a698d2d.png)
URL: https://staging.pergoflooring.com/shop/rigid-vinyl/extreme-enhanced/detail/PT003-180/ayres?title=Pergo%20Extreme%20Wood%20Enhanced

Also getting a 400 error for all options on URL: https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000961/crema-oak?title=Pergo%20Portfolio%20+WetProtect
![image](https://user-images.githubusercontent.com/83465286/116756176-4a9d1680-a9d1-11eb-9266-762c2bb4d0f5.png)

Please advise when we can test.

**Comment by savithanuguri** [comment]
@rmessickSDI this is an issue is related to Hybris. They are not having all products. For your test Please use 
https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000967/rustic-smoke-chestnu?title=Pergo%20Portfolio%20+WetProtect
https://staging.pergoflooring.com/shop/rigid-vinyl/extreme-options/detail/PT004-009/bennington?title=Pergo%20Extreme%20Tile%20Options
https://staging.pergoflooring.com/shop/rigid-vinyl/extreme-enhanced/detail/PT003-180/ayres?title=Pergo%20Extreme%20Wood%20Enhanced
https://staging.pergoflooring.com/shop/rigid-vinyl/extreme-originals/detail/PT001-552/angel-dust?title=Pergo%20Extreme%20Wood%20Originals

**Comment by rmessickSDI** [comment]
https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000967/rustic-smoke-chestnu?title=Pergo%20Portfolio%20+WetProtect
test on and looks to fire correctly.
![image](https://user-images.githubusercontent.com/78565036/117206534-99bfbe80-adb8-11eb-844f-c569c96b54bd.png)

**Comment by ryanAtSdi** [comment]
@savithanuguri - is there an issue with cart? I tried the provided links, but am seeing a number of errors, and therefore cannot add anything to cart:

![image](https://user-images.githubusercontent.com/83465286/118309986-9cef3480-b4b3-11eb-9685-6c8cf40c4a7d.png)

**Comment by savithanuguri** [comment]
@ryanAtSdi There is an ongoing issue in QA commerce cloud and trying to restart the services.

**Comment by savithanuguri** [comment]
@ryanAtSdi  Add to Cart issue is resolved. Please test and let me know

**Comment by ryanAtSdi** [comment]
Thank you, @savithanuguri ! Confirming it's working now. I'll close this ticket out. 
![image](https://user-images.githubusercontent.com/83465286/118825105-05595f80-b880-11eb-8196-ef9aafb281ed.png)
