### ISSUE TITLE
User Signed In - Multiple JS Events Firing

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#54]
When you sign-in to the site, there too many events firing. After pushing the sign-in button the sign-in event and for succeeded events fire as they should, but then all of these events fire:

![image](https://user-images.githubusercontent.com/72522616/117011715-1ae55b80-acbc-11eb-9ea8-a51e78b849ad.png)

There are many page load starts, completes, user detected, location detected events happening here that should not be occuring.

**Comment by savithanuguri** [comment]
@jasonegan deployed on staging
![image](https://user-images.githubusercontent.com/82102160/117901339-24149080-b299-11eb-8df9-3245336eca63.png)
