### ISSUE TITLE
Cart Viewed - Incorrect DL Values for brand, productLine, and productID

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#55]
On Cart Viewed event, DL values for brand, productLine, and productID are incorrect. brand, productLine are coming through as undefined, and productID is sent to "" (blank). 

![image](https://user-images.githubusercontent.com/83465286/117205264-05a12780-adb7-11eb-8c16-edfefbaf2d07.png)

**Comment by ryanAtSdi** [comment]
@savithanuguri - the fix resolved the issue with values passing, but it may have caused another issue related to the data layer not updating properly when an item is removed from cart.

When validating, I added a sample from: https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000967/rustic-smoke-chestnu?title=Pergo%20Portfolio%20+WetProtect. Then, I removed it, added it back, and viewed the cart. Upon viewing the data layer, I see 2 samples listed, even though only 1 was in the cart. See the screenshot below:
![image](https://user-images.githubusercontent.com/83465286/118057681-0fe09a00-b352-11eb-98b1-5e7539456876.png)

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/118169238-b8483a00-b3f6-11eb-9cfe-fa5d719196c7.png)

@ryanAtSdi Following the exact same process with the same product, I'm unable to replicate this for some reason. Is it still happening on your end?

**Comment by savithanuguri** [comment]
@ryanAtSdi , We did changes in staging. Please test
