### ISSUE TITLE
Cart Viewed - event fires 2x in DL 

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#56]
On cart view, Cart Viewed event is fired twice in the DL:
![image](https://user-images.githubusercontent.com/83465286/117205772-ae4f8700-adb7-11eb-8738-8d0ed412a8d5.png)

**Comment by savithanuguri** [comment]
@ryanAtSdi , updated code and available in staging
![image](https://user-images.githubusercontent.com/82102160/117903942-76a47b80-b29e-11eb-92ba-b8c39f43e57e.png)
