### ISSUE TITLE
Checkout Started - No event in DL after starting checkout/incorrect values

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#57]
No event in DL after clicking "Checkout" button and beginning checkout process:
![image](https://user-images.githubusercontent.com/83465286/117206932-089d1780-adb9-11eb-801a-9d911d6bb429.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119759654-9b8c1780-be76-11eb-961b-bfae0e41d50a.png)
@ryanAtSdi available in staging

**Comment by ryanAtSdi** [comment]
@savithanuguri - Confirming the event is there now, but the name is incorrect--it should include the color.

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/120039601-36016d80-bfd3-11eb-8159-2580fddd031d.png)
@ryanAtSdi
