### ISSUE TITLE
Form Submission Succeeded - Form ID, Form Name, Form Type not sent to AA

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#58]
v29-31 in data layer but not server call:
![image](https://user-images.githubusercontent.com/83465286/117482675-51c0a900-af2a-11eb-8632-fd94146b35bf.png)

**Comment by rmessickSDI** [comment]
Put in a ticket with apollo team.
https://apolloplatform.atlassian.net/browse/AP-1733

**Comment by rmessickSDI** [comment]
Pushed fix from Apollo.

**Comment by ryanAtSdi** [comment]
Confirming v29-31 are present on server call:
![image](https://user-images.githubusercontent.com/83465286/122611770-7d65a180-d047-11eb-94bd-ceb9783a5f3e.png)
