### ISSUE TITLE
Retail Filter Removed - Wrong value in data layer

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#60]
When removing a filter from the location search, "retailerType~all" is being passed rather than the filter that was removed.

![image](https://user-images.githubusercontent.com/83465286/117696249-b0825e80-b186-11eb-97c5-776db2d641a5.png)

**Comment by savithanuguri** [comment]
@ryanAtSdi , code available in staging
![image](https://user-images.githubusercontent.com/82102160/117908000-c0449480-b2a5-11eb-915e-c5f38f906830.png)
