### ISSUE TITLE
Retailer Listing Item Clicked - Location position and details not sent to AA

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#61]
When clicking a retailer from the listing page, e26 fires, but none of the item position or location details are sent to AA, but are present in data layer. 

![image](https://user-images.githubusercontent.com/83465286/117698290-31daf080-b189-11eb-9c66-f56362cc81ca.png)

**Comment by rmessickSDI** [comment]
@rmessickSDI need to add fakeProductId in launch rule.

**Comment by rmessickSDI** [comment]
@jasonegan Should we set the locationId as the productid or use the fake one?

**Comment by ryanAtSdi** [comment]
@jasonegan - any update on this one?

**Comment by rmessickSDI** [comment]
![image](https://user-images.githubusercontent.com/78565036/121220759-8934b500-c84a-11eb-8e92-441d657e2eb6.png)

**Comment by ryanAtSdi** [comment]
@rmessickSDI - I see the listing twice (i.e., 2 product stings). I assume this is expected--first is for location detected, second for location listing item clicked--but wanted to confirm before closing the ticket out. 

![image](https://user-images.githubusercontent.com/83465286/121241472-18e55e00-c861-11eb-8ae8-5325fd616aa2.png)

**Comment by ryanAtSdi** [comment]
Confirmed this is correct w/ Rickey on June 9 discussion. Closing ticket.
