### ISSUE TITLE
Onsite Search Performed - Location search not firing to AA

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#62]
When searching a zip from the Find a Retailer page (https://staging.pergoflooring.com/shop/find-a-retailer), data layer is populated but no server call occurs:
![image](https://user-images.githubusercontent.com/83465286/117700481-ae6ece80-b18b-11eb-8da7-95668f5e9c6b.png)

**Comment by rmessickSDI** [comment]
I checked again and is working.  May have been fixed when I pushed apollo events on another issue.

**Comment by rmessickSDI** [comment]
Added beacon call to apollo and pushed.  `Onsite Search Performed` search fires then the new page starts to load.

**Comment by rmessickSDI** [comment]
![image](https://user-images.githubusercontent.com/78565036/118137453-d5ffaa00-b3ca-11eb-8e7f-b6c0d86d2780.png)
Ready to retest
