### ISSUE TITLE
Sample Added to Cart - Multiple incorrect values in data layer

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#63]
On Sample Added to Cart event, following issues with data layer values exist:

- **brand** is being populated with the product name, rather than Pergo
- **businessUnit** is blank
- **isSample** is set to false, despite a sample being added to cart

Can be tested on: https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000967/rustic-smoke-chestnu?title=Pergo%20Portfolio%20+WetProtect 

Screenshot: 
![image](https://user-images.githubusercontent.com/83465286/117731903-83e53b80-b1b4-11eb-8baf-1df90243f1bf.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/117918898-ff7ce080-b2b9-11eb-8de0-b4f01d1ceca8.png)
@ryanAtSdi

**Comment by ryanAtSdi** [comment]
@savithanuguri - I believe we need ticket #73 resolved in relation to what values should be set for each product eVar. Ideally, the values passed to each eVar should align to how you think about/report on things internally (@rmessickSDI , @jasonegan - keep me honest there). 

The issue we're having now is that is seems these values are changing somewhat regularly, so it's difficult to QA as we don't know what to expect. 

Perhaps for this ticket, we just focus on businessUnit grabbing some value, and isSample being set correctly. As long as those are correct, the ticket can be closed out, and specific values can be handled via #73. Does that work?

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/118754689-8e977480-b835-11eb-83e4-2311ccffe965.png)
@ryanAtSdi , We updated based on input from Julia. Please check and let me know.

**Comment by ryanAtSdi** [comment]
@savithanuguri - in the screenshot above, name is still incorrect, as color should be included.

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119167286-b2bda600-ba2d-11eb-9785-7eebc69f9643.png)

@ryanAtSdi Deployed in dev. After deployment to staging will update

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119352383-9d37be80-bc6f-11eb-8e37-2ffa15c49d13.png)

@ryanAtSdi , deployed in staging
