### ISSUE TITLE
Form Submission Failed - e18 shows twice in AA server call

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#64]
When an form submission fails, seeing e18=1 appear 2x in AA server call, but it's only listed in data layer once. Can replicate issue by using wrong credentials here: https://staging.pergoflooring.com/login

![image](https://user-images.githubusercontent.com/83465286/117822860-825a5880-b232-11eb-8f9f-a34e24d3a05f.png)

**Comment by rmessickSDI** [comment]
https://apolloplatform.atlassian.net/browse/AP-1752
