### ISSUE TITLE
Location Detected - Location Name not in AA server call

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#65]
When location detected event fires in data layer, Location Name is present but not sent on server call. Can replicate here: https://staging.pergoflooring.com/

![image](https://user-images.githubusercontent.com/83465286/117826485-cef36300-b235-11eb-8827-1f8d1a6201a2.png)

**Comment by rmessickSDI** [comment]
https://apolloplatform.atlassian.net/browse/AP-1670

**Comment by rmessickSDI** [comment]
Need to set to real location id in apollo.

**Comment by rmessickSDI** [comment]
![image](https://user-images.githubusercontent.com/78565036/118138009-75bd3800-b3cb-11eb-94f9-a7f4872f88b5.png)
https://staging.pergoflooring.com/

Fixed.  It is setting now.
