### ISSUE TITLE
Location Detected - Location Determination Method has wrong value on server call, but correct in data layer

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#66]
On location detected event, Location Determination Method has wrong value on server call, but correct in data layer. Replicate here: https://staging.pergoflooring.com/

![image](https://user-images.githubusercontent.com/83465286/117827304-77a1c280-b236-11eb-93b6-3e6681f20ad2.png)

**Comment by rmessickSDI** [comment]
https://apolloplatform.atlassian.net/browse/AP-1670

**Comment by rmessickSDI** [comment]
![image](https://user-images.githubusercontent.com/78565036/118318559-2d7f4200-b4bf-11eb-9862-dee7d25dbbf1.png)
