### ISSUE TITLE
Video Events - What's a URL with a video?

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#67]
When trying to QA all events related to videos, I'm having a little trouble finding one. I was expecting some on the DIY and cleaning pages, but don't see any. Can you please point me in the right direction?

Thanks!

**Comment by nate-wolfe** [comment]
You're in the right place, there should be two videos on [Install & DIY](https://staging.pergoflooring.com/install-diy). Not sure why those aren't showing, I'll look into it

**Comment by ryanAtSdi** [comment]
Thank you, @nate-wolfe , @savithanuguri !

**Comment by ryanAtSdi** [comment]
@nate-wolfe, @savithanuguri - going to move this to "in progress" until the videos are back on the site. I just checked again, and 4/5 accordions weren't working, and no videos were available.

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/118067634-f1d56280-b36e-11eb-89bf-7e59bee5c4c0.png)
@ryanAtSdi video component is working properly
