### ISSUE TITLE
User Signed In - multiple data layer events firing after login

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#68]
After a user signs in, Page Load Started, Page Load Complete, User Detected, and Location Detected are fire 2x - 4x, which then results in a large number of extra server calls. 

![image](https://user-images.githubusercontent.com/83465286/117833781-3dd3ba80-b23c-11eb-9e5c-46f1c64e5841.png)

**Comment by savithanuguri** [comment]
@ryanAtSdi , deployed in staging
![image](https://user-images.githubusercontent.com/82102160/117901282-fcbdc380-b298-11eb-9d8b-8cd0798082ea.png)
