### ISSUE TITLE
Bloomreach - pixel implementation

### ISSUE THREAD

**Issue by rmessickSDI** [searchdiscovery/mohawk-flooring-dl-spec#69]

**Comment by jasonegan** [comment]
@rmessickSDI Just wanted to note that my recent ticket on the breadcrumbs in Github was so that we can properly use that in the Bloomreach pixel's "Category" specification.

**Comment by rmessickSDI** [comment]
We have all these implemented.  
![image](https://user-images.githubusercontent.com/78565036/122428101-4021e680-cf57-11eb-9fa7-59e2c00f9399.png)

@savithanuguri Can we see if bloomreach can confirm these pixels are flowing in correctly?

**Comment by rmessickSDI** [comment]
verified with Bloomreach on call.  Created ticket for product id and cat they are needing.  Dev team will need to add to DL.
