### ISSUE TITLE
User Signed In - Beacon call quadruple fires

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#70]
On sign in, 4 beacons are sent, but only 1 sign-in event in data layer:
![image](https://user-images.githubusercontent.com/83465286/118170313-90a1a380-b3ef-11eb-81b1-47a5ff0ceb3d.png)

**Comment by rmessickSDI** [comment]
This is fixed now.
![image](https://user-images.githubusercontent.com/78565036/118529628-56931300-b709-11eb-8c02-024c4908a671.png)
