### ISSUE TITLE
Product Comparison Viewed - multiple data layer values appear incorrect

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#71]
When looking at product comparison after completing quiz, data layer does not match what's displayed to user.
**trademarkTechnology** - expecting Key Benefits items, not Product Type
**name/productLine** - expecting one of these to match the names listed in the comparison, the other to be the collection the name belongs to. Can the team please provide some guidance on expected values here? 

Given it's not clear the items above are correct, also unclear as to whether or not **productID** and **sku** are correct. Can we please have some guidance here as well--should these values be the same?

![image](https://user-images.githubusercontent.com/83465286/118175313-900c0b80-b3f5-11eb-8d6c-1f1c8a60486d.png)

**Comment by nate-wolfe** [comment]
As per Julia recently, productLine and name should be very similar, with name being the specific color of the product. Since in this context, we're only referring to broader collections, I would think they should be the same.

ProductID and SKU shouldn't be the same. ProductID is right here, but SKU definitely isn't.

**Comment by ryanAtSdi** [comment]
@jasonegan, @savithanuguri - for this event, shouldn't we be passing productID, not sku? 

From the latest email, productID here is correct, but sku should either: 1)be the long format or 2)not exist. Otherwise, reporting on sku will be a hodgepodge of values.

**Comment by jasonegan** [comment]
@savithanuguri Hold on this until we can discuss internally here. Thanks!

**Comment by jasonegan** [comment]
@savithanuguri Can you change this event name to "Collection Comparison Viewed"?

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/120039853-942e5080-bfd3-11eb-813a-eae95cd09f5a.png)
@jasonegan , changed name as Collection Comparison Viewed

**Comment by ryanAtSdi** [comment]
Closing ticket as event was renamed correctly. Specific data layer values will be addressed via ticket #88
