### ISSUE TITLE
Launch General - beacons double firing

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#72]
When QAing visualizer, saw beacon double firing even though only 1 event in data layer. However, it looks like it's happening for other events as well. 

To replicate, view visualizer from this page: https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000967/rustic-smoked-chestnut?title=Pergo%20Portfolio%20+WetProtect

![image](https://user-images.githubusercontent.com/83465286/118179377-d57f0780-b3fa-11eb-8798-fa21f866f113.png)

**Comment by rmessickSDI** [comment]
Worked with Michael to sync all from apollo again.  There were duplicate events in rules for some reason.
