### ISSUE TITLE
Product Listing Displayed - multiple incorrect data layer issues

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#75]
On PLPs, multiple incorrect data layer values are passed:

- Product Listing Position (v40) - starts at 0, rather than 1, which could potentially be confusing for those using data in reporting
- Product color (v59) - values listed in data layer do not match what is displayed on the page
- Listing Sort Default Value (v35) - data layer has 2, but expecting actual filter value (i.e., "Featured")

![image](https://user-images.githubusercontent.com/83465286/118303850-8b099380-b4ab-11eb-8b6a-5c2935ebd28e.png)

![image](https://user-images.githubusercontent.com/83465286/118304027-c0ae7c80-b4ab-11eb-9d9d-5575e12c49f1.png)

**Comment by savithanuguri** [comment]
@ryanAtSdi There was a filter for sort and having 3 values as featured, review, and status. But for this release, it is out of scope. In the code commented.

**Comment by ryanAtSdi** [comment]
Thank you, @savithanuguri . What about for v40 and v59? Are those in scope for this release?

**Comment by ryanAtSdi** [comment]
@savithanuguri - I checked this today and noticed that the product string on the PLP is different from on Product Click:
![image](https://user-images.githubusercontent.com/83465286/118867556-d60b1880-b8a8-11eb-96ef-5f81e250fb4e.png)

**Comment by nate-wolfe** [comment]
@ryanAtSdi @jasonegan @rmessickSDI 
For [Product Listing Displayed](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Product%20Listing%20Displayed.md), the specification is unclear. Since we list collections, not products, these listings inherently have no productId, color, or any other item-specific value. 
How should we adjust this event? We could add another layer of arrays to list all the product data per product within each collection displayed, or we could simply choose the first of available data, though this would be largely inaccurate.

**Comment by ryanAtSdi** [comment]
@nate-wolfe, @savithanuguri - given ticket #88 addresses productID, productLine color, name, and sku across all events, let's just focus on remaining data layer issues for the Product Listing Displayed event on this ticket. 

I've reviewed that event in the data layer again today, and observed that trademarkedTechnology is listing SpillProtect twice. The event is correct otherwise.
![image](https://user-images.githubusercontent.com/83465286/120553744-7b9cac80-c3be-11eb-9b92-64e40ef6e199.png)

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/121378893-94064d00-c911-11eb-9a3e-485fb88c0b59.png)
Duplicate trademarkedTechnology value has been removed

**Comment by ryanAtSdi** [comment]
@nate-wolfe , @savithanuguri - when I go to the all products PLP (here: https://staging.pergoflooring.com/shop?installation=&look=&page=1), there are no products at all in the Product Listing Displayed event:

![image](https://user-images.githubusercontent.com/83465286/121414692-8ca06d00-c92c-11eb-8af9-ca253c7277f3.png)

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/122268537-2d050d00-ceaa-11eb-9101-6ff8b0045c49.png)
I believe this is working correctly now.
