### ISSUE TITLE
Product Listing Item Clicked & Product Viewed - AA beacon not firing

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#76]
After clicking a product from a PLP, CTA Link Clicked is firing but not Product Listing Item Clicked, despite being in data layer. On Product Viewed, only location is passed via product string:

![image](https://user-images.githubusercontent.com/83465286/118306868-91017380-b4af-11eb-8cce-f0c92e658487.png)

**Comment by rmessickSDI** [comment]
added beacon call to `Product Listing Item Clicked`
![Uploading image.png…]()
