### ISSUE TITLE
User Signed In - User ID undefined in data layer. 

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#77]
On sign-in event, User ID (v49) is set to undefined in the data layer:
![image](https://user-images.githubusercontent.com/83465286/118550242-0b392e80-b722-11eb-860a-9541ba248c63.png)

@savithanuguri - will the ID be present at the time of the event, or will this not be ready until the following page load?

**Comment by savithanuguri** [comment]
@ryanAtSdi 
![image](https://user-images.githubusercontent.com/82102160/118757178-9279c580-b83a-11eb-8b90-1e6233338e98.png)
After login, this value will be available
