### ISSUE TITLE
Product Collection Viewed - More info needed

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#79]
@savithanuguri - What pages should we be using for the Product Collection Viewed event? Or, is this really the same as a Listing Viewed + Listing Filter Added, and therefore not actually needed. 

Tha nks!

**Comment by savithanuguri** [comment]
@ryanAtSdi , We have already implemented Product Viewed. Let me know the difference between Product Collection Viewed and Product Viewed

**Comment by ryanAtSdi** [comment]
@savithanuguri - I didn't believe there was a difference, but wanted to confirm. Thank you!
