### ISSUE TITLE
Page Load Started - Prop2 not sent on server call

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#81]
On page load started, Prop2 is present and correct in data layer, but not sent on server call:
![image](https://user-images.githubusercontent.com/83465286/118839072-d0530a00-b88b-11eb-818e-3f86da75518e.png)

**Comment by rmessickSDI** [comment]
@savithanuguri Can we get this to be `page.breadcrumbs` the `c` being lowercase?

CC @ryanAtSdi

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119755438-09811080-be70-11eb-9097-57f67aa0eab5.png)
Updated breadcrumbs available in staging
