### ISSUE TITLE
Adobe Launch - Report Suite ID "CHANGE_ME"

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#82]
Looks like the report suite ID in the beacon is coming across as "CHANGE_ME" and needs to be updated.
![image](https://user-images.githubusercontent.com/72522616/119036791-28b70400-b97f-11eb-8566-d23d0c08b3dd.png)

**Comment by rmessickSDI** [comment]
push library to prod and it fixed it.
![image](https://user-images.githubusercontent.com/78565036/119497552-58249280-bd2a-11eb-8e8f-04d833578c0b.png)
