### ISSUE TITLE
Product Interaction Occurred - Set Selected Tab - Incorrect v62 value in data layer

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#83]
When clicking a tab on a PDP, the data layer includes the name of the tab the user clicked from, rather than the tab they clicked to. 

In the example below, I clicked FROM "Warranty and Install" TO "The Collection", but data layer records that "Warranty and Install" was clicked:
![image](https://user-images.githubusercontent.com/83465286/119055029-345df700-b98e-11eb-8afa-9ed82182c38c.png)

![image](https://user-images.githubusercontent.com/83465286/119054854-f2cd4c00-b98d-11eb-877e-3127e9be019d.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119353495-f81de580-bc70-11eb-9b84-6a8bcbe5a6af.png)
@ryanAtSdi , Deployed in staging. Please test
