### ISSUE TITLE
Page Load Started - breadCrumbs

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#84]
Page breadcrumb need to be the full breadcrumb and not just the most detailed portion. This is also needed for the Bloomreach pixel implementation.

Example Page: https://staging.pergoflooring.com/shop/laminate/outlast/detail/LF000850/antique-cherry?title=Pergo%20Outlast+%20with%20SpillProtect

Visible Breadcrumb on page:
![image](https://user-images.githubusercontent.com/72522616/119141255-079ff300-ba13-11eb-8b91-4e43ee8d643a.png)

Current Data Layer value for "breadCrumbs:"
![image](https://user-images.githubusercontent.com/72522616/119141336-21d9d100-ba13-11eb-8995-1ad0592ed954.png)

We would expect the breadcrumb here to either match what is on the visible page, or to be what is in pageName, excluding the detail of the page itself, such as:
pergo:shop:laminate:outlast

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119190483-6b461280-ba4b-11eb-917a-5581bc832141.png)
@jasonegan , deployed in staging.

**Comment by ryanAtSdi** [comment]
@savithanuguri - still seeing the issue on some pages. See details below.
**URL:** https://staging.pergoflooring.com/shop/easy-diy?installation=beginnerInstallation&look=&page=1

**Data Layer Screenshot:**
![image](https://user-images.githubusercontent.com/83465286/119196190-64b79b00-ba4b-11eb-9731-3ce32b7dad79.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119759262-f2ddb800-be75-11eb-8dc9-27b8329bbb7d.png)
@ryan, updated in staging

**Comment by ryanAtSdi** [comment]
@savithanuguri - I'm still seeing this set incorrectly in multiple places. See screenshots below comparing data layer to the expected value. Note, I didn't check every single page, just a few to grab some examples.

https://staging.pergoflooring.com/shop?installation=&look=&page=1
![image](https://user-images.githubusercontent.com/83465286/119858258-ec812780-bed9-11eb-908b-b796ab27f946.png)

https://staging.pergoflooring.com/install-diy#gettingstarted
![image](https://user-images.githubusercontent.com/83465286/119859381-f48d9700-beda-11eb-876d-0c412d9c82a2.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119989929-bef9b400-bf95-11eb-9ce8-edb5e1761d33.png)
![image](https://user-images.githubusercontent.com/82102160/119990007-d3d64780-bf95-11eb-88f5-1fbe4f5a7f11.png)

@ryanAtSdi  Added in all places and available in staging

**Comment by ryanAtSdi** [comment]
@savithanuguri - I'm still seeing this incorrect in some cases. On the homepage, this should be set to pergo:home for consistency. On the contact page, this is being set to undefined.

@rmessickSDI , @jasonegan - could you provide a little more guidance on how this should be formatted? To me, it would make be clearer to do: pergo:home > pageName (parsed after ":"), but I may just be getting knit-picky there.

![image](https://user-images.githubusercontent.com/83465286/120005489-7fcf6100-bf9d-11eb-8b2b-38d86d28aff0.png)

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/122268111-af410180-cea9-11eb-9b9b-eaab887e0429.png)
![image](https://user-images.githubusercontent.com/81365619/122268132-b536e280-cea9-11eb-97e2-c1a6c2b0ef14.png)
This is now showing pergo:home and pergo:contact-us, respectively, in staging.

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/122271540-815dbc00-cead-11eb-8fff-740518f24823.png)
Currently, Contact Us breadcrumbs are correct in staging. 

Pending merge of a PR, the home page breadcrumbs will appear as follows: 
![image](https://user-images.githubusercontent.com/81365619/122271998-0d6fe380-ceae-11eb-8a64-c4257a806798.png)
