### ISSUE TITLE
Order Placed - Multiple incorrect/missing data layer values

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#85]
When placing an order, the following are missing or incorrect in the data layer:

- Ship to postal code - missing
- Ship to state or province - missing
- Product name - incorrect value
- Product color - set to null
- Product line - incorrect value
- Product price tier - missing
- Product trademarked technology - incorrect value
- Ship to country - missing
- Price - missing
- Purchase ID - incorrect value

![image](https://user-images.githubusercontent.com/83465286/119407073-51a20680-bca9-11eb-99e6-2e37147bc1c9.png)

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/121378604-59041980-c911-11eb-8550-21a0b7ec76e4.png)

**Comment by ryanAtSdi** [comment]
@nate-wolfe , @savithanuguri - There are a few items that either look incorrect or I have a questions about:

- purchaseID and transactionID are still blank. Is this just a limitation of the staging site?
- stateProvince is still blank
- Should price be a number, rather than a string? (@rmessickSDI , @jasonegan - you may have insight here as well)

![image](https://user-images.githubusercontent.com/83465286/121409776-7a700000-c927-11eb-9c4b-15d90200d1ba.png)

**Comment by nate-wolfe** [comment]
As per Savitha, we won't have either of the IDs, as these values aren't available.

**Comment by ryanAtSdi** [comment]
Sounds good. I will close this out then. Thank you, @nate-wolfe

**Comment by ryanAtSdi** [comment]
Quantity incorrect under following scenario:

1. Log in, and place a sample in your cart.
2. Log out, and place another sample for the same item in your cart.
3. Go to checkout. You should be asked to sign in. Upon doing so, you will see both samples in your cart. 
4. Place order. The order will be for 2 samples, but quantity is 1 in data layer. 

![image](https://user-images.githubusercontent.com/83465286/122779408-73c08180-d273-11eb-876c-d1eb1c276865.png)

**Comment by nate-wolfe** [comment]
In order to add this value, I'll need to add it to Cart Viewed as well. I doubt that'll be a problem as we can simply ignore it.

**Comment by nate-wolfe** [comment]
In staging:
![image](https://user-images.githubusercontent.com/81365619/123286326-d1ef9d80-d4db-11eb-8ac2-40f35ec82280.png)
![image](https://user-images.githubusercontent.com/81365619/123286580-06635980-d4dc-11eb-9283-4ddb60d00935.png)

**Comment by ryanAtSdi** [comment]
@nate-wolfe - is this ready for us to review?

**Comment by nate-wolfe** [comment]
@ryanAtSdi It should be. I don't have access to move the tickets, but I believe the changes are all on staging.
