### ISSUE TITLE
Order Placed - Adobe beacon not firing

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#86]
When an order is placed the Order Placed event is in the data layer, but no beacon is fired. 
![image](https://user-images.githubusercontent.com/83465286/119407939-911d2280-bcaa-11eb-8332-3eba633d76c0.png)

**Comment by rmessickSDI** [comment]
I see the order placed event fire.
![image](https://user-images.githubusercontent.com/78565036/119510179-ef8fe280-bd36-11eb-9e90-8c3fb1e7debd.png)

Do not see the productId being set in DL.  @savithanuguri  Can you take a look at this?

![image](https://user-images.githubusercontent.com/78565036/119510100-de46d600-bd36-11eb-8966-dba26e141ccc.png)

**Comment by rmessickSDI** [comment]
Ok it is firing now.
![image](https://user-images.githubusercontent.com/78565036/119512613-164f1880-bd39-11eb-8075-5d716518267a.png)

@savithanuguri The productId is not populating correctly.
![image](https://user-images.githubusercontent.com/78565036/119513337-c02ea500-bd39-11eb-8db4-a89f6d2788af.png)

**Comment by rmessickSDI** [comment]
A separate ticket for productId issue.
