### ISSUE TITLE
Checkout Started - Product string not sent on server call

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#87]
on scCheckout, only location is sent via product string, but product info is in data layer:

![image](https://user-images.githubusercontent.com/83465286/119862727-6c10f580-bede-11eb-885b-f43cdf4d62c9.png)

**Comment by rmessickSDI** [comment]
This is happening due to checkout started fires and then location detection fires which both have Product String Builder.  There is a patch for this being released any day for this.  Once it is there should combine products.

**Comment by ryanAtSdi** [comment]
Thank you, @rmessickSDI! Is the patch related to a Launch Ticket, or something else?

**Comment by rmessickSDI** [comment]
After Launch upgraded tested again see DL issue.  Created ticket for it.  https://github.com/searchdiscovery/mohawk-flooring-dl-spec/issues/91
