### ISSUE TITLE
Product ID Update - Change in Value

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#88]
Regardless what may conceptually be a product ID, this value in Adobe Analytics is what should be the same from the top of the conversion funnel all the way to Order Placed. In the case of Pergo, this seems to be "Product Line." So, we would like to replace the value of "productID" in all product/item arrays as a part of the implementation. This change would need to be made in the following events:

1. Cart Viewed
2. Checkout Started
3. Product Added to Cart
4. Product Collection Viewed
5. Product Interaction Occurred
6. Collection Comparison Viewed
7. Product Listing Displayed
8. Product Listing Item Clicked
9. Product Removed from Cart
10. Product Viewed
11. Visualizer Viewed

- Additional Collection Comparison Viewed and Product Listing Displayed change: Replace product ID as noted above and also do NOT set color, name or sku (as the comparison is not at the lowest level)

**Comment by jasonegan** [comment]
@savithanuguri Just noting here as per our conversations that we'll be adding "productNumber" into all of the applicable arrays above. With the exception of the "Collection Comparison Viewed" event.

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/121379241-d62f8e80-c911-11eb-947e-08847fb17066.png)

**Comment by ryanAtSdi** [comment]
@nate-wolfe , @savithanuguri  - is this ready for QA in staging?

**Comment by nate-wolfe** [comment]
@ryanAtSdi Yes, I believe so.

**Comment by ryanAtSdi** [comment]
Thank you, @nate-wolfe ! We'll get started on it now!

**Comment by ryanAtSdi** [comment]
Noticed the following data layer issues. See attached file for additional details. 

**Collection Comparison Viewed:** 
- color, name, and sku still being passed
- productId is incorrect (matches name instead of product line

**Product Listing Displayed:**
- color, name, sku, and productNumber still being passed
[Pergo - Product String Values by Event.xlsx](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/files/6640976/Pergo.-.Product.String.Values.by.Event.xlsx)

**Comment by nate-wolfe** [comment]
Product Listing Displayed has been corrected and the change is visible on staging:
![image](https://user-images.githubusercontent.com/81365619/122272370-79524c00-ceae-11eb-884d-7bc1cc82ef43.png)

Collection Comparison Viewed was updated, but had some issues that are pending the merge of a PR. Once that is merged, this is the result:
![image](https://user-images.githubusercontent.com/81365619/122272830-cafad680-ceae-11eb-8c18-dc00a78c5b6a.png)
