### ISSUE TITLE
Product Listing Clicked - Incorrect data layer value(s)

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#89]
On product listing clicked, I am seeing "SpillProtect" listing twice in data layer:
![image](https://user-images.githubusercontent.com/83465286/120507773-b980dd00-c38c-11eb-918a-03b3b2c3007e.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/120797439-09d17980-c50a-11eb-9dd5-3c431a4cd416.png)
@ryanAtSdi removed Spillprotect
