### ISSUE TITLE
Exit Link Clicked - Link ID "Null"

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#9]
On a dealer info page (ex: [Johnson & Sons Flooring](https://staging.pergoflooring.com/shop/find-a-retailer/9721/Johnson-&-Sons-Flooring)) there is a button to click to see reviews. This is in an external link:

![image](https://user-images.githubusercontent.com/72522616/114064320-837d1c00-9867-11eb-8cf7-e19914c607d4.png)

When clicking this link, "[Exit Link Clicked](https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Exit%20Link%20Clicked.md)" event fires, but the "linkID" value is null. Here, we'd expect something such as "view all ratings." This value could be. the link text, button text, image alt text, image url if no alt text exists, etc.

![image](https://user-images.githubusercontent.com/72522616/114064491-b58e7e00-9867-11eb-83c7-84c62f3b98d9.png)

**Comment by cumeakunne** [comment]
linkId has been set to "View All Ratings" when "Exit Link Clicked" event fires. 
![image](https://user-images.githubusercontent.com/60761366/115066654-da18d480-9ebd-11eb-888e-516630258678.png)
