### ISSUE TITLE
Order Placed - add payment amount

### ISSUE THREAD

**Issue by rmessickSDI** [searchdiscovery/mohawk-flooring-dl-spec#90]
https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Order%20Placed.md
![image](https://user-images.githubusercontent.com/78565036/120528057-a24bea80-c3a0-11eb-9636-a0eaf4fda8ae.png)

**Comment by jasonegan** [comment]
@savithanuguri We need this for the completion of pixels such as Bloomreach.

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/121378656-64574500-c911-11eb-9535-dc6571d2cc94.png)

**Comment by ryanAtSdi** [comment]
@rmessickSDI - assigning over to you, as the paymentAmount isn't being sent over to on the sever call:

**Server Call**
![image](https://user-images.githubusercontent.com/83465286/122779882-edf10600-d273-11eb-8883-591f166e1cf0.png)

**Data Layer**
![image](https://user-images.githubusercontent.com/83465286/122780042-137e0f80-d274-11eb-94d5-30cf46835968.png)

**Comment by rmessickSDI** [comment]
This is fixed now. 
![image](https://user-images.githubusercontent.com/78565036/122833444-9a51dd00-d2b2-11eb-9f54-a0aea267597e.png)

**Comment by ryanAtSdi** [comment]
Confirming this is resolved:
![image](https://user-images.githubusercontent.com/83465286/123132964-e7e65b00-d414-11eb-8713-1751fb8ce470.png)
