### ISSUE TITLE
Checkout Started - DL issue - params added

### ISSUE THREAD

**Issue by rmessickSDI** [searchdiscovery/mohawk-flooring-dl-spec#91]
<img width="552" alt="Screen Shot 2021-06-03 at 10 35 52 AM" src="https://user-images.githubusercontent.com/78565036/120672092-9bcc7a00-c457-11eb-9120-6397753be54f.png">
`params` should not be there.

https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Cart%20Viewed.md

To reproduce go to:
https://staging.pergoflooring.com/shop/laminate/portfolio/detail/LF000967/rustic-smoked-chestnut?title=Pergo%20Portfolio%20+WetProtect
Add to cart then checkout.  

See problem on this page:
https://staging.pergoflooring.com/checkout

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/121379539-1db61a80-c912-11eb-8f25-9819ce91ec3f.png)
