### ISSUE TITLE
Product Removed From Cart - No event in data layer

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#92]
When trying to remove an item from the cart, I am not seeing the corresponding event present in the data layer for any method of removing an item from cart. The removal methods tested include:

- Remove button on PDP
- Clicking trash can icon in cart
- Clicking "Clear Cart" link in cart
- Changing quantity to "0", then clicking "update" link in cart

Screenshot below shows data layer after clicking "Clear Cart" link, but I see the same thing for all 4 removal methods
![image](https://user-images.githubusercontent.com/83465286/120707887-77d15e80-c480-11eb-802a-435346d305e1.png)

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/122268348-f3cc9d00-cea9-11eb-8734-faec925b4ef6.png)
The event is now present.
