### ISSUE TITLE
Product Interaction Occurred - Product Visualization (v67) blank on non-visualizer events

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#93]
@savithanuguri - on the product interaction occurred events, I am seeing v67 set to blank anytime the interaction is not related to the visualizer (see example below). I want to confirm this is expected before updating the status in the QA document. 

![image](https://user-images.githubusercontent.com/83465286/120818072-e281a900-c517-11eb-89af-1b9b22a050ad.png)

**Comment by savithanuguri** [comment]
@ryanAtSdi , this is expected. Only for visualizer providing the value

**Comment by ryanAtSdi** [comment]
Thank you, @savithanuguri !
