### ISSUE TITLE
Location Listing Displayed - Not all locations displayed

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#94]
When viewing a Locations Listing Page not all locations are sent through on server call, but they are present in the data layer.

URL: https://staging.pergoflooring.com/shop/find-a-retailer?zip=78717&page=1&filter=all

![image](https://user-images.githubusercontent.com/83465286/120820299-080fb200-c51a-11eb-9061-875acf447732.png)

**Comment by rmessickSDI** [comment]
@ryanAtSdi I am seeing this now.  

https://staging.pergoflooring.com/shop/find-a-retailer?zip=92252&page=1&filter=all

![image](https://user-images.githubusercontent.com/78565036/121088854-f6453d80-c7ab-11eb-87dd-5310fc350998.png)

**Comment by ryanAtSdi** [comment]
Confirming we're good here:
![image](https://user-images.githubusercontent.com/83465286/121094738-b3d42e80-c7b4-11eb-9367-61f0b9b30579.png)
