### ISSUE TITLE
Location Listing item Clicked and Location Selected split on Listing Page

### ISSUE THREAD

**Issue by rmessickSDI** [searchdiscovery/mohawk-flooring-dl-spec#95]
@savithanuguri  

Can we get these events split on the location listing page?

etc https://staging.pergoflooring.com/shop/find-a-retailer?zip=37129&page=1&filter=all

Right now

<img width="1052" alt="Screen Shot 2021-06-09 at 11 39 20 AM" src="https://user-images.githubusercontent.com/78565036/121395199-c61aad80-c917-11eb-9ba6-ea22e7648e4c.png">

CC @ryanAtSdi

**Comment by nate-wolfe** [comment]
Upon clicking 'Make This My Retailer':
![image](https://user-images.githubusercontent.com/81365619/122268754-72293f00-ceaa-11eb-9303-517e6964cba1.png)

Upon clicking any of the other three: 
![image](https://user-images.githubusercontent.com/81365619/122268846-9127d100-ceaa-11eb-96de-c948081928c1.png)

These events have now been split, and this change is visible in staging.
