### ISSUE TITLE
Product Number Addition

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#96]
Need to add "Product Number" to Apollo for the following events once Apollo has been updated.

![image](https://user-images.githubusercontent.com/72522616/121571287-d0f54100-c9f0-11eb-9ae5-50c2ecb47a69.png)

**Comment by rmessickSDI** [comment]
Pushed from apollo for these events.
![image](https://user-images.githubusercontent.com/78565036/122450850-196eaa80-cf6d-11eb-9cfc-85fef6eca611.png)

**Comment by ryanAtSdi** [comment]
Confirming this looks good! 

![image](https://user-images.githubusercontent.com/83465286/122453804-3a84ca80-cf70-11eb-8399-d3b85d6b60fe.png)
