### ISSUE TITLE
Onsite Search Performed - add searchTermCorrected

### ISSUE THREAD

**Issue by rmessickSDI** [searchdiscovery/mohawk-flooring-dl-spec#98]
https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Onsite%20Search%20Performed.md

This is for bloomreach pixels addition.

https://documentation.bloomreach.com/developers/search-and-merchandising/pixel-deployment/event-pixels/suggest-event-pixel.html

"searchTerm": "<searchTerm>",  // e.g. "woven scarf"
"searchTermCorrected": "<searchTermCorrected>",  // e.g "wo"

**Comment by jasonegan** [comment]
@rmessickSDI This is apparently in place in staging at this time. Do we already both of these Bloomreach pixels in place, or were we waiting for this to be implemented before we added the pixels?

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/122264891-19f03e00-cea6-11eb-8d55-0f41daf75489.png)
Upon searching for 'Timber' and clicking the suggestion for Timbercraft

**Comment by rmessickSDI** [comment]
![image](https://user-images.githubusercontent.com/78565036/122296513-1ff31880-cec0-11eb-8d02-f4429020ffac.png)
@savithanuguri Can you confirm this is good with bloomreach?

**Comment by ryanAtSdi** [comment]
@rmessickSDI - with the update, I'm seeing the beacon double fire:
![image](https://user-images.githubusercontent.com/83465286/122781053-0d3c6300-d275-11eb-91a4-38edd2a37b14.png)

**Comment by rmessickSDI** [comment]
pushed clear vars for onsite search performed.  Fixed now.
![image](https://user-images.githubusercontent.com/78565036/122830352-d767a080-d2ad-11eb-90e4-e7f75a6e048c.png)

**Comment by ryanAtSdi** [comment]
Confirming this is good now:
![image](https://user-images.githubusercontent.com/83465286/123132175-0bf56c80-d414-11eb-8c2d-61c3f7c2e494.png)
